import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../styles/globals.css";
import Image from 'next/image';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import Header from '@/components/Header';
import Footer from '@/components/Footer';



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Header />
        <div className="logo-fixed">
          <a href="/">
            <Image
              src="/kabuchan/logo.png"
              alt="かぶちゃんロゴ"
              width={500}
              height={250}
            />
          </a>
        </div>
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
